version: '3.1'

services:
    tests:
        container_name: tests
        build: 
            context: .
        networks:
            - orchestration
        volumes: 
            - ./:/usr/src/code


networks:
    orchestration: